;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-word-begin
        evil-digit-argument-or-evil-beginning-of-line
        evil-first-non-blank
        evil-forward-char
        evil-insert
        evil-join
        evil-next-line
        evil-normal-state
        evil-substitute
        evil-yank
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-ex
        evil-exit-visual-state
        evil-find-char
        evil-force-normal-state
        evil-forward-word-begin
        evil-previous-line
        evil-repeat-find-char-reverse
        evil-ret
        evil-search-next
        evil-set-marker
        evil-visual-char
        kill-region
        paredit-forward-slurp-sexp
        smex
        ))
